# Generated by Django 6.0.4 on 2026-05-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.CharField(default='01.01.2000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='Test', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Test', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
